filebeat.modules:
  - module: zeek
    connection:
      enabled: true
      var.paths: ["/sample-pcaps/conn.log"]
    dns:
      enabled: true
      var.paths: ["/sample-pcaps/dns.log"]
    http:
      enabled: true
      var.paths: ["/sample-pcaps/http.log"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

setup.ilm.enabled: false
index: "zeek-%{+yyyy.MM.dd}"

processors:
  - add_fields:
      target: ""
      fields:
        project: "soc-autonomo"

