filebeat.modules:
  - module: zeek
    connection:
      enabled: true
      var.paths: ["/logs/conn.log"]
    dns:
      enabled: true
      var.paths: ["/logs/dns.log"]
    http:
      enabled: true
      var.paths: ["/logs/http.log"]
    weird:
      enabled: true
      var.paths: ["/logs/weird.log"]
    notice:
      enabled: true
      var.paths: ["/logs/notice.log"]
      

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

setup.ilm.enabled: false
index: "zeek-%{+yyyy.MM.dd}"

processors:
  - add_fields:
      target: ""
      fields:
        project: "soc-autonomo"

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false